# Generated by Django 5.0.2 on 2024-03-12 20:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AttendanceModel",
            fields=[
                (
                    "date",
                    models.DateField(
                        default=datetime.datetime.now, primary_key=True, serialize=False
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VideoFeedModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(default=False)),
                ("url", models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="StudentModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "attendances",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="Ai_backend.attendancemodel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="attendancemodel",
            name="student_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student",
                to="Ai_backend.studentmodel",
            ),
        ),
    ]
